### ISSUE TITLE
[MAME 2003] Galaga does not work

### ISSUE THREAD

**Issue by drrak** [libretro/libretro-meta#101]
_Google translator:_
Please do something to make it possible to run this game.

Thank you for your help.

RPi3, RetroArch 1.6.7, Gamestarter 8.167.4

**Comment by dankcushions** [comment]
it works fine. get the correct romset. please close this issue.

**Comment by meepingsnesroms** [comment]
Newer mame versions are more accurate, some older versions used HLE(emulating only what you see but not what should actually happen) in place of actual game emulation like an mp3 instead of emulating the audio cpu.

The newer roms dont contain the mp3 and the older roms dont contain the audio cpu executable so some roms for mame 2003 wont work on 2010 and some for 2010 wont work on 2003.
