### ISSUE TITLE
[lr-snes9x] Phalanx (all regions) freezes on a black screen after choosing to begin the game. Does not occur on lr-snes9x2010

### ISSUE THREAD

**Issue by MapleStoryPSN** [libretro/libretro-meta#90]
Hardware/version used: Raspberry Pi 3 running RetroPie 4.2.12

lr-snes9x core version shown in Retroarch: SNES9x 1.54.1 4030c32

Roms tested: Phalanx (USA).zip/Phalanx (Europe).zip/Phalanx - The Enforce Fighter A-144 (Japan).zip from no-intro set.

The game loads fine but upon selecting "EXECUTE MISSION" after pressing start at the title screen to begin the game, it locks up on a black screen and retroarch becomes unresponsive (requiring the process to be killed). The same issue occurs if you wait for the demo gameplay at the title screen.

The game fires up with no problems on lr-snes9x2010.

**Comment by hizzlekizzle** [comment]
Can you try this in non-libretro Snes9x 1.54?

**Comment by MapleStoryPSN** [comment]
Just downloaded and installed standalone Snes9x 1.54 and 1.54.1 (tested both 32 and 64 bit) on my Windows 10 PC. Can confirm that the game does not start on 1.54 or 1.54.1 at all, chokes at the same exact moment.

**Comment by hizzlekizzle** [comment]
Ah, very interesting. This is probably related to the new APU that was introduced in v1.54, which is much more accurate than the old one and allowed them to kill off a bunch of hacks in the code. However, it's had less testing (obviously) than the old one, so some bugs have cropped up (that's why there's a 1.54.1 release, IIRC; to squash some of them).

**Comment by hizzlekizzle** [comment]
I spoke too soon! It doesn't appear to be related to the new APU. Instead, it seemed to be related to a code refactor designed to fix some compiler warnings.

I wasn't able to reproduce it using upstream's libretro interface.

I do sometimes get a black screen (i.e., the program doesn't lock up but the game doesn't progress either), but it resolves if I close and relaunch, so that could be something more squirrelly.

I'm going to close this, but feel free to reopen it if the problem persists.
